# Files and Directories
music_directory    "~/.local/share/music"
playlist_directory "~/.local/share/music/playlists"
db_file "~/.config/mpd/database"
#db_file            "~/.local/share/mpd/database"
#log_file           "~/.local/share/mpd/log"
#pid_file           "~/.local/share/mpd/pid"
#state_file         "~/.local/share/mpd/state"
#sticker_file       "~/.local/share/mpd/sticker.sql"

# Network Settings
bind_to_address    "127.0.0.1"
port               "6600"
restore_paused     "yes"
auto_update        "yes"

# Audio Output (Modern PipeWire/PulseAudio setup)
audio_output {
        type "pipewire"
        name "PipeWire Sound Server"
}


# Alternative: Uncomment this if you are using standard PulseAudio instead of PipeWire
#audio_output {
#        type            "pulse"
#        name            "PulseAudio"
#}
