#!/usr/bin/env bash
ln -sf ~/.cache/wal/colors.Xresources ~/.Xresources
cat ~/.Xresources ~/.cache/wal/xrdb_extra | xrdb -merge
xdotool key super+F5 # xrdb refresh keybind
# ln -sf ~/.cache/wal/colors-obsidian.css ~/dotfiles/helpbook/.obsidian/snippets/colors-obsidian.css

