#!/bin/bash
./tailscale-remove-node
sudo systemctl stop tailscaled
sudo rm -rf /var/lib/tailscale/
sudo systemctl daemon-reload
sudo systemctl start tailscaled
sudo tailscale set --operator=$USER
if [ -z "${TAILSCALE_AUTHKEY:-}" ]; then
	echo "Error: TAILSCALE_AUTHKEY not set" >&2
	exit 1
fi
tailscale up --auth-key="$TAILSCALE_AUTHKEY"
tailscale set --exit-node=100.78.208.61
