[open]
rules = [
    { mime = "text/*", use = "edit" },
    { mime = "image/*", use = "image" },
    { mime = "video/*", use = "video" },
    { mime = "{audio,application}/*", use = "video" },  # mpv i dlya audio
]

[opener]
#edit = [
#  { run = 'nvim "$@"', desc = "Edit in NVIM", block = true }
#]
#image = [
#    { run = 'loupe "$@"', block = true, orphan = true }
#]
video = [
    { run = 'mpv "$@"', desc = "Open with mpv" }
]

[mgr]
show_hidden = true

